name = "chiyigo-com"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "chiyigo_db"
database_name = "chiyigo_db"
database_id = "59f73214-1203-44b7-840f-86cb3998fbb6"
